name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: make install-tools

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16.3"

      - name: Build service
        run: make build


